
package RestaurantSelector2;


public class RestaurantLoader1 {
  public int loadRestaurants(){
  Restaurant.createRestaurant("Rafele Restaurante", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Olio e Piú", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Raviolo", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Buvette", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Cotenna", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("The Meatbal Shop", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Piccolo Angolo Restaurant", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Kestè", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Gottino", "Italian", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Hakata Tonton", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Ramen-Ya", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("E.A.K Ramen", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Sushi Para 88", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("PokeRice", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Mew Men", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Rockmeisha", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Asami Shanghai", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Kumo", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Mikado", "Japanese", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Perry St", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Boucherie", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("33 Greenwich", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Fedora", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("The Little Owl", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("La Ripaille", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("La Sirene", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("Bagatelle", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("BOBO", "French", "WestVillage", "Inexpensive");
  Restaurant.createRestaurant("ABC kitchen", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("The NoMad restaurant", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Bouley Test Kitchen", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Eleven Madison Park", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("French1", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("French2", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("French3", "French", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Eataly", "Italian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Basta Pasta", "Italian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Ulivo", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Zero Otto Nove", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Sotosuolo NYC", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Via Emilia", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Waldy’s Wood Fired Pizza & Penne", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Union Fare", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Bread and Tulips", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Union Fare", "Itlalian", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Izakaya NoMad", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Tsurutontan Udon Noodle Brasserie", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Bao Bao Cafe", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Ootoya", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("KazuNori", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Sushirrito", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Wagamama", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Chikarashi", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Mira", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("MoMo", "Japanese", "Flatiron", "Inexpensive");
  Restaurant.createRestaurant("Il Mattone", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Da Mikele", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Saluggis", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Sole di Capri", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("L'Angolo", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Terra Wine Bar", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("hank's Juicy Beef", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Antica Ristorante", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Estancia 460", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Zutto", "Italian", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("B Flat", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Takahachi", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Kaede", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Tataki", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Tokyo Bay", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Shinjuku", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("JR Sushi", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Hamachi", "Japanese", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Bouley", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Batard", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("R", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("The O", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("MAt", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Le Co", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("B", "French", "Tribeca", "Inexpensive");
  Restaurant.createRestaurant("Bar B", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("The Meatball Shop2", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Pepe Giallo", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Momofuku", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Ovest Pizzoteca", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Zia Maria", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Hold My Knots", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Zagara", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Claudio", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Bottino", "Italian", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Jun-Men Ramen", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Oramen", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Kobeyaki", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Juban", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Asuka", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Mokbar", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Maru 2", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Ajisen Ramen", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Sushi Tokyo", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Tabata", "Japanese", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("French1", "French", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("French2", "French", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("French3", "French", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("French4", "French", "Chelsea", "Inexpensive");
  Restaurant.createRestaurant("Rafele Restaurante", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("L'Artusi", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Palma", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Barbuto", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("dell'anima", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Morandi", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Via Carota", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("I Sodi", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Lupa", "Italian", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Babbo", "Italian", "WestVillage", "Expensive"); 
  Restaurant.createRestaurant("Takashi", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Sushi Nakazawa", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Omakase Room by Tatsu", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Saikai", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("EN Japanese Brasseri", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Kosaka", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("DOMODOMO", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Naoki", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Sushi Samba", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("MoriMoto", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Catch", "Japanese", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Perry St", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Boucherie", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Le Giot", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Fedora", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Little Owl", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("La Rapaille", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Sirene", "French", "WestVillage", "Expensive");
  Restaurant.createRestaurant("Maialino", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Marta", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Giorgio's of Gramercy", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Zio Ristorante", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Manzo Ristorante", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Obica Mozzarella Bar Pizza e Cucina", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Osteria del Principe", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("fusco", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Italienne", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Novita Restaurant", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Paul& JImmy's", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Mamma Guidara's", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("I Trulli", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Trattoria Il Mulino", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Bocca Restaurant & Bar", "Italian", "Flatiron", "Expensive");
  Restaurant.createRestaurant("O Ya", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("TEISUI", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Yakiniky Futago", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Roki Le IZakaya", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("15 East Restaurant", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("SUGARFISH by sushi nozawa", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Hillstone", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Blue Water Grill", "Japanese", "Flatiron", "Expensive"); 
  Restaurant.createRestaurant("Hanjan", "Japanese", "Flatiron", "Expensive");
  Restaurant.createRestaurant("ABC kitchen", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("The NoMad Restaurant", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Bouley Test Kitchen", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Eleven Madison Park", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Italliene", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Tocqueville Restaurant", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Le Coq Rico", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Le Restaurant d'Alex", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Boqueria", "French", "Flatiron", "Expensive");
  Restaurant.createRestaurant("Pepolino Restaurant", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Locanda Verde", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Scalini Fedeli", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Gran Morsi", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Ecco", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Tutto il Giorno", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("etrarca Cucina E Vino", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Mamo", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Osteria Morini", "Italian", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Shigure", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Sushi Azabu", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Ichimura", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("BrushStroke", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Takahachi Tribeca Restaurant", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Ninja New York", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Sushi of Gari", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("HiroHisa", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Blue Ribbon", "Japanese", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Bouley", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Batard", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Racine", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Odeon", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Mamo", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Sirene", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Baltazar", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("LeCoucou", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Taureau", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("L'Appart", "French", "Tribeca", "Expensive");
  Restaurant.createRestaurant("Del Posto", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Mulino a Vino", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Scarpetta", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Da Umberto", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("La Sirena", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Cassa Nona", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Crispo", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Il Bastardo", "Italian", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Ushiwakamaru", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Juban", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Naoki", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Morimoto", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Momoya", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Kappo Totto", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Megu", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Sushi Seki-Chelsea", "Japanese", "Chelsea", "Expensive");
  Restaurant.createRestaurant("Mykonos Blue", "French", "Chelsea", "Expensive");
  Restaurant.createRestaurant("periyali", "French", "Chelsea", "Expensive");
  Restaurant.createRestaurant("La Piscine", "French", "Chelsea", "Expensive");
 return 1;  

  }
}
